/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.ejs',
    './src/**/*.js',
    './src/**/*.ts',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#EFF6FF',
          500: '#3B82F6',
          600: '#2563EB',
          700: '#1D4ED8',
        },
        // Action-success green (Run / Apply / Applied). Matches --jh-sb-green used by .jh-btn-success.
        success: {
          600: '#28B169',
          700: '#178049',
        },
        // Design System v2 tokens (DESIGN_SYSTEM_v2.md §1.1) — CSS vars defined in src/styles/tailwind.css.
        ds: {
          bg: 'var(--bg)',
          card: 'var(--card)',
          panel: 'var(--panel)',
          ink: 'var(--ink)',
          ink2: 'var(--ink2)',
          muted: 'var(--muted)',
          muted2: 'var(--muted2)',
          faint: 'var(--faint)',
          fainter: 'var(--fainter)',
          faintest: 'var(--faintest)',
          line: 'var(--line)',
          line2: 'var(--line2)',
          line3: 'var(--line3)',
          accent: 'var(--accent)',
          'accent-hover': 'var(--accent-hover)',
          'accent-soft': 'var(--accent-soft)',
          'accent-border': 'var(--accent-border)',
          'accent-tint': 'var(--accent-tint)',
          green: 'var(--green)',
          green2: 'var(--green2)',
          'green-soft': 'var(--green-soft)',
          'green-border': 'var(--green-border)',
          red: 'var(--red)',
          'red-ink': 'var(--red-ink)',
          'red-soft': 'var(--red-soft)',
          'red-border': 'var(--red-border)',
          'amber-soft': 'var(--amber-soft)',
          'amber-border': 'var(--amber-border)',
          'amber-ink': 'var(--amber-ink)',
          purple: 'var(--purple)',
          'purple-soft': 'var(--purple-soft)',
          'sky-soft': 'var(--sky-soft)',
          'sky-ink': 'var(--sky-ink)',
          'sky-border': 'var(--sky-border)',
        },
      },
      borderRadius: {
        'ds-chip': 'var(--radius-chip)',
        'ds-btn': 'var(--radius-btn)',
        'ds-input': 'var(--radius-input)',
        'ds-card': 'var(--radius-card)',
        'ds-dropdown': 'var(--radius-dropdown)',
        'ds-modal': 'var(--radius-modal)',
        'ds-pill': 'var(--radius-pill)',
      },
      boxShadow: {
        'ds-card': 'var(--shadow-card)',
        'ds-card-hover': 'var(--shadow-card-hover)',
        'ds-selected': 'var(--shadow-selected)',
        'ds-dropdown': 'var(--shadow-dropdown)',
        'ds-popover': 'var(--shadow-popover)',
        'ds-modal': 'var(--shadow-modal)',
        'ds-list-edge': 'var(--shadow-list-edge)',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'Helvetica', 'Arial', 'sans-serif'],
      },
    },
  },
};
